name: ML Model Development

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: docker

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Test with pytest
        run: pytest train/test_train.py

      - name: Train and evaluate model
        run: python train/train.py

      - name: build Docker image
        run: docker build -t ml-model .
        
      - name: Login to Docker Hub
        run: echo ${{ secrets.PASSWORD }} | docker login -u ${{ secrets.USERNAME }} --password-stdin

      - name: Tag docker image
        run: docker tag ml-model ${{ secrets.USERNAME }}/ml-model

      - name: Push docker image
        run: docker push ${{ secrets.USERNAME }}/ml-model

